### ISSUE TITLE
Issues on using a child Theme

### ISSUE THREAD

**Issue by daniel-pimenta-DME** [ALMiG-Kompressoren-GmbH/tailcloakify#56]
Hi,

I've been trying to extend tailcloakify theme to customize some styles, but unable to so far.
I've imported tailcloakify jar file into keycloak's providers folder, and created a theme called identity4eo which extends from Tailcloakify. 

![Image](https://github.com/user-attachments/assets/cf8a7c7f-7d7e-41bf-80a1-f3f817069711)

Keycloak recognizes it and it's loaded and configured:
![Image](https://github.com/user-attachments/assets/1303dfd5-56a1-4aba-b7dc-00903fba6575)

But my resources are not loaded and not used:

![Image](https://github.com/user-attachments/assets/abc65b00-112b-44a5-96ea-606d74a2e7a6)

**Additional info**
keycloak version: 26.2.0
tailcloakify jar: https://github.com/ALMiG-Kompressoren-GmbH/tailcloakify/releases/download/v1.1.9/keycloak-theme-for-kc-all-other-versions.jar
environment: custom docker image with docker compose
dockerfile:
```
ARG VERSION=26.2.0

FROM quay.io/keycloak/keycloak:${VERSION} AS build
ARG KC_FEATURES=recovery-codes,scripts,passkeys,update-email
ENV KC_DB=postgres
ARG KC_HEALTH_ENABLED=true
ARG KC_TRACING_ENABLED=true
ADD --chown=keycloak:keycloak providers /opt/keycloak/providers
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:${VERSION}
ENV DISABLE_EXTERNAL_ACCESS=true
COPY --from=build /opt/keycloak/ /opt/keycloak/
ADD --chown=keycloak:keycloak data/import /opt/keycloak/data/import
ADD --chown=keycloak:keycloak themes /opt/keycloak/themes
COPY providers/keycloak-metrics-spi-7.0.0.jar /opt/keycloak/providers
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

Is there anything i'm missing?
Any help is appreciated, thanks.

**Comment by waynemorphic** [comment]
Hi @daniel-pimenta-DME, I will be happy to help 

Ideally, to use custom styles from your `login.css` file, you will need to target keycloak classes. Some of these classes are marked with the prefix `kc-`.  Please check out [this guide](https://docs.keycloakify.dev/css-customization) for more information, or explore the doc for how to extend Tailcloakify or Keycloakify. Please let me know if this answers your question

**Comment by daniel-pimenta-DME** [comment]
Hi @waynemorphic 

Thanks for the help.
I believe my issue is not related to wrongly using css selectors. My resource files aren't being loaded.

My styles.css contains only the following:
```
body {
    background-color: #004254;
}
```

which works when my theme extends from keycloak.v2:

![Image](https://github.com/user-attachments/assets/64e98a37-6c57-4efc-ad83-0eb4bec1dfd8)

but not when it extends from Tailcloakify:

![Image](https://github.com/user-attachments/assets/d4d0c22b-87a6-4906-b0e2-f95e38a0c38c)

**Comment by waynemorphic** [comment]
Okay, allow me to investigate further @daniel-pimenta-DME . Are all the above the steps to reproduce the issue?

**Comment by daniel-pimenta-DME** [comment]
> Okay, allow me to investigate further [@daniel-pimenta-DME](https://github.com/daniel-pimenta-DME) . Are all the above the steps to reproduce the issue?

The following steps should be enough to reproduce it:

1. dockerfile
```
ARG VERSION=26.2.0

FROM quay.io/keycloak/keycloak:${VERSION} AS build
ENV KC_DB=postgres
ARG KC_HEALTH_ENABLED=true
ARG KC_TRACING_ENABLED=true
ADD --chown=keycloak:keycloak providers /opt/keycloak/providers
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:${VERSION}
ENV DISABLE_EXTERNAL_ACCESS=true
COPY --from=build /opt/keycloak/ /opt/keycloak/
ADD --chown=keycloak:keycloak data/import /opt/keycloak/data/import
ADD --chown=keycloak:keycloak themes /opt/keycloak/themes
COPY providers/keycloak-metrics-spi-7.0.0.jar /opt/keycloak/providers
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

**Comment by daniel-pimenta-DME** [comment]
> Okay, allow me to investigate further [@daniel-pimenta-DME](https://github.com/daniel-pimenta-DME) . Are all the above the steps to reproduce the issue?

The following steps should be enough to reproduce it:

1. structure
tailcloakify.jar
themes
Dockerfile
docker-compose.yaml

2. tailcloakify.jar downloaded from https://github.com/ALMiG-Kompressoren-GmbH/tailcloakify/releases/download/v1.1.9/keycloak-theme-for-kc-all-other-versions.jar

3. themes following the usual keycloak's theme structure
themes > theme_name > login > theme.properties
```
parent=Tailcloakify
styles=css/styles.css
favIcon=img/favicon.png
logo=img/logo.png
locales=en,pt
```
themes > theme_name > login > resources > css > styles.css
```
body {
    background-color: #004254;
}
```


4. Dockerfile

```
ARG VERSION=26.2.0

FROM quay.io/keycloak/keycloak:${VERSION} AS build
ENV KC_DB=postgres
ADD --chown=keycloak:keycloak tailcloakify.jar /opt/keycloak/providers/tailcloakify.jar
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:${VERSION}
COPY --from=build /opt/keycloak/ /opt/keycloak/
ADD --chown=keycloak:keycloak themes /opt/keycloak/themes
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

5. docker-compose

```
volumes:
  db:
services:
  keycloak:
    build:
      dockerfile: Dockerfile
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_STRICT=false
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --optimized
    restart: on-failure
    depends_on:
      - database
  database:
    image: postgres:17.0
    container_name: keycloak-db
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=123
      - ALLOW_IP_RANGE=0.0.0.0/0
      - FORCE_SSLL=TRUE
      - TIMESCALEDB_TELEMETRY=off
      - PGDATA=/var/lib/postgresql/data/keycloak
    restart: on-failure
```

6. docker compose up -d --build

7. docker compose down -v
